//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elk.UpdateableLinks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elk.UpdateableLinks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Transaction(TransactionMode.Manual)]
        ///public class [#LINKCLASSNAME#] : IExternalCommand
        ///{
        ///	public string Name 
        ///	{
        ///		get { return &quot;[#LINKNAME#]&quot;; }
        ///	}
        ///	public string ToolTip
        ///	{
        ///		get { return &quot;[#LINKTOOLTIP#]&quot;; }
        ///	}
        ///	public string Icon
        ///	{
        ///		get { return &quot;[#LINKICON#]&quot;; }
        ///	}
        ///	public string ButtonId
        ///	{
        ///		get { return &quot;[#BUTTONID#]&quot;; }
        ///	}
        ///	public string ButtonType
        ///	{
        ///		get { return &quot;[#BUTTONTYPE#]&quot;; }
        ///	}
        ///	public string ButtonName
        ///	{
        ///		get { return &quot;[#BUTTONNAME#]&quot;; }
        ///	}
        ///	public string [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommandStarter {
            get {
                return ResourceManager.GetString("CommandStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DefaultButton {
            get {
                object obj = ResourceManager.GetObject("DefaultButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Diagnostics;
        ///using System.Reflection;
        ///using Autodesk.Revit;
        ///using Autodesk.Revit.Attributes;
        ///using Autodesk.Revit.DB;
        ///using Autodesk.Revit.UI;
        ///using RevitCommon;
        ///
        ///namespace Elk.ContentLinks
        ///{
        ///	[#COMMANDS#]
        ///}.
        /// </summary>
        internal static string LinkStarter {
            get {
                return ResourceManager.GetString("LinkStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap manageButton {
            get {
                object obj = ResourceManager.GetObject("manageButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
